server:
  port: 8086
  servlet:
    context-path: /car-ecommerce

spring:
  application:
    name: car-service
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/car-ecommerce
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true


